openapi: 3.0.0
info:
  title: 'Larynx'
  version: '1.0'
  description: 'Larynx Text to Speech API'
paths:
  /api/tts:
    get:
      summary: 'Speak text to WAV'
      parameters:
        - name: voice
          in: query
          required: true
          description: 'Voice in the form [language]/[name]-[tts_system]'
          schema:
            type: string
            example: 'en-us/harvard-glow_tts'
        - in: query
          name: text
          required: true
          description: 'Text to speak'
          schema:
            type: string
            example: 'Hello world!'
        - in: query
          name: vocoder
          description: 'Vocoder in the form [vocoder_system]/[model_name]'
          schema:
            type: string
            example: 'hifi_gan/universal_large'
        - in: query
          name: denoiserStrength
          description: 'Strength of vocoder denoiser (0-1, 0 is disabled)'
          schema:
            type: number
            example: 0.002
        - in: query
          name: noiseScale
          description: 'Volatility of speaker (0-1, default: 0.667, GlowTTS only)'
          schema:
            type: number
            example: 0.667
        - in: query
          name: lengthScale
          description: 'Speed of speaker (default: 1.0, faster &lt; 1 &lt; slower, GlowTTS only)'
          schema:
            type: number
            example: 0.85
        - in: query
          name: ssml
          description: 'Input text in SSML'
          schema:
            type: boolean
            example: false
      responses:
        '200':
          description: audio
          content:
            audio/wav:
              schema:
                type: string
                format: binary
    post:
      summary: 'Speak text to WAV'
      requestBody:
        required: true
        description: 'Text to speak'
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - in: query
          name: voice
          required: true
          description: 'Voice in the form [language]/[name]-[tts_system]'
          schema:
            type: string
            example: 'en-us/harvard-glow_tts'
        - in: query
          name: vocoder
          description: 'Vocoder in the form [vocoder_system]/[model_name]'
          schema:
            type: string
            example: 'hifi_gan/universal_large'
        - in: query
          name: denoiserStrength
          description: 'Strength of vocoder denoiser (0-1, 0 is disabled)'
          schema:
            type: number
            example: 0.002
        - in: query
          name: noiseScale
          description: 'Volatility of speaker (0-1, default: 0.667, GlowTTS only)'
          schema:
            type: number
            example: 0.667
        - in: query
          name: lengthScale
          description: 'Speed of speaker (default: 1.0, faster &lt; 1 &lt; slower, GlowTTS only)'
          schema:
            type: number
            example: 0.85
        - in: query
          name: ssml
          description: 'Input text is SSML'
          schema:
            type: boolean
            example: false
      responses:
        '200':
          description: audio
          content:
            audio/wav:
              schema:
                type: string
                format: binary
  /api/voices:
    get:
      summary: 'Get available voices'
      responses:
        '200':
          description: voices
          content:
            application/json:
              schema:
                type: object
  /api/vocoders:
    get:
      summary: 'Get available vocoders'
      responses:
        '200':
          description: vocoders
          content:
            application/json:
              schema:
                type: object
  /api/phonemes:
    get:
      summary: 'Get phonemes for language'
      parameters:
        - in: query
          name: language
          required: true
          description: 'Gruut language code'
          schema:
            type: string
            example: 'en-us'
      responses:
        '200':
          description: phonemes
          content:
            application/json:
              schema:
                type: object
