name: Python CI
concurrency: 
  group: main
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: Build production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel setuptools flake8
        pip install -r requirements.txt
        pip install .
    - name: Lint with flake8
      run: |
        flake8 . --verbose